name: Deploy to Heroku(Backend)

on: [push]
  
defaults:
   run:
      working-directory: server
       
jobs:
  build:       
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy backend to Heroku
        run: git push https://heroku:${{secrets.HEROKU_API_TOKEN}}@git.heroku.com/${{secrets.HEROKU_BACKEND_APP_NAME}}.git :refs/head/master --force
