name: Deploy to Heroku(Backend)

on: [push]
  
defaults:
   run:
      working-directory: server
       
jobs:
  build:       
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to heroku Container registry
        env: 
          HEROKU_API_TOKEN: ${{secrets.HEROKU_API_TOKEN}}
        run: heroku container:login
      